var movieList = [	
'The Big Short',
'Bridge of Spies',
'Brooklyn',
'Mad Max',
'The Martian',
'The Revenant',
'Room',
'Spotlight',
'American Sniper',
'Birdman',
'Boyhood',
'Grand Budapest Hotel',
'The Imitation Game',
'Selma',
'The Theory of Everything',
'Whiplash',
'12 Years a Slave',
'American Huslte',
'Captain Phillips',
'Dallas Buyers Club',
'Gravity',
'Her',
'Nebraska',
'Philomena',
'Wolf of Wall Street',
'Argo',
'Amour',
'Beast of the southern wild',
'Django',
'Les Mis',
'Life of Pi',
'Lincoln',
'Silver Linings Playbook',
'Zero Dark Thirty',
'The Artist',
'The Descendants',
'Extremely Loud and Incredibly Close',
'The Help',
'Hugo',
'Midnight in Paris',
'Moneyball',
'The Tree of Life',
'War Horse',
'The Kings Speech',
'127 Hours',
'Black Swan',
'The Fighter',
'Inception',
'The Kids are all right',
'The social network',
'Toy Story 3',
'True Grit',
'Winters Bone',
'The Hurt Locker',
'Avatar',
'District 9',
'An Education',
'Inglorious Bastards',
'Precious',
'A serious Man',
'Up',
'Up in the air',
'Slumdog millionaire',
'Frost/Nixon',
'Milk',
'The Reader',
'No Country for Old Men',
'Antonement',
'Juno',
'Michael Clayton',
'There will be blood',
'The Departed',
'Babel',
'Letters from Iwo Jima',
'Little Miss Sunshine',
'The Queen',
'Crash',
'Brokeback mountain',
'Capote',
'Good Night and Good Luck',
'Munich',
'Million Dollar Baby',
'Aviator',
'Finding Neverland',
'Ray',
'Sideways',
'LOTR',
'Lost in translation',
'master and commander',
'mystic river',
'seabuscuit',
'chicago',
'gangs of new york',
'the hours',
'LOTR',
'The pianist',
'Godsford Park',
'A beautiful mind',
'In the bedroom',
'LOTR',
'Moulin Rouge',
'Gladiator',
'Choclat',
'Crouching tiger hidden dragon',
'Erin Brockovich',
'Traffic',
'American Beauty',
'The cider house',
'The green mile',
'The insider',
'The sixth sense',
'Shakespear in love',
'Elizabeth',
'Life is beautiful',
'saving private ryan',
'the thin red line',
'Titanic',
'As good as it gets',
'the full monty',
'good will hunting',
'L.A. Confidential',
'The English Patient',
'Fargo',
'Jerry Maguire',
'Secrets & Lies',
'Shine',
'Braveheart',
'Apollo 13',
'Babe',
'II Postino',
'Sense and Sensibility',
'Forrest Gump',
'Four Weddings and a Funeral',
'Pulp Fiction',
'Quiz Show',
'The Shawshank Redemption',
'Schindler\'s List',
'The Fugitive',
'In the Name of the father',
'The Piano',
'The Remains of the Day',
'Unforgiven',
'The Crying Game',
'A Few Good Men',
'Howards End',
'Scent of a Woman',
'Silence of the Lambs',
'Beauty and the Beast',
'Bugsy',
'JFK',
'The Prince of Tides',
'Dances with Wolves',
'Awakenings',
'Ghost',
'The Godfather',
'Goodfellas',
'Driving Miss Daisy',
'Born on the Fourth of July',
'Dead Poets Society',
'Field of Dreams',
'My Left Foot'
]












